-- Create "dotsource_path" table
CREATE TABLE "dotsource_path" ("id" serial NOT NULL, "base_path" character varying(255) NOT NULL DEFAULT '/repository_storage', "relative_path" character varying(255) NULL DEFAULT '', "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create "app_user" table
CREATE TABLE "app_user" ("id" serial NOT NULL, "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "photo_url" character varying(255) NOT NULL DEFAULT 'https://robohash.org/71d2d83d09151874f9bdfecc0da05d6a?set=set4&bgset=&size=400x400', "email_verified" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create "dotsource" table
CREATE TABLE "dotsource" ("id" serial NOT NULL, "user_id" integer NOT NULL, "dotsource_path_id" integer NOT NULL, "name" character varying(255) NOT NULL, "private" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "dotsource_dotsource_path_id_fkey" FOREIGN KEY ("dotsource_path_id") REFERENCES "dotsource_path" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "dotsource_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "preferences" table
CREATE TABLE "preferences" ("id" serial NOT NULL, "user_id" integer NOT NULL, "dark_mode" boolean NOT NULL DEFAULT true, "codespace_theme" character varying(255) NOT NULL DEFAULT 'dracula', "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "refresh_token" table
CREATE TABLE "refresh_token" ("id" serial NOT NULL, "user_id" integer NOT NULL, "token" character varying(255) NOT NULL, "client_ip" character varying(255) NOT NULL, "expires_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "refresh_token_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
