services:
  dottie-go:
    container_name: dotty-go-container
    image: dottie-go
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.dev
    volumes:
      - ./:/app
      - repository_storage:/repository_storage
    ports:
      - "8080:8080"
    env_file:
      - .env.dev


  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db:5432
      ADMINER_DESIGN: dracula
    restart: always
    ports:
      - 7777:8080
volumes:
  repository_storage:
  database_data: