// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const createAppUser = `-- name: CreateAppUser :one
INSERT INTO app_user ("name", "email", "password") VALUES ($1, $2, $3) RETURNING  id, name, email, password, photo_url, email_verified, created_at, updated_at, deleted_at
`

type CreateAppUserParams struct {
	Name     string
	Email    string
	Password string
}

func (q *Queries) CreateAppUser(ctx context.Context, arg CreateAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser, arg.Name, arg.Email, arg.Password)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.PhotoUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
